
INSERT INTO BOARD (NAME) VALUES ('Prvi board');

INSERT INTO BOARD_LIST (NAME, BOARD_ID) VALUES ('Prva lista',1);

INSERT INTO CARD (CONTENT, BOARD_LIST_ID) VALUES ('Prva kartica', 1);
INSERT INTO CARD (CONTENT, BOARD_LIST_ID) VALUES ('Druga kartica', 1);

INSERT INTO BOARD_LIST (NAME, BOARD_ID) VALUES ('Druga lista',1);

INSERT INTO CARD (CONTENT, BOARD_LIST_ID) VALUES ('Treca kartica', 2);
INSERT INTO CARD (CONTENT, BOARD_LIST_ID) VALUES ('Cetvrta kartica', 2);
INSERT INTO CARD (CONTENT, BOARD_LIST_ID) VALUES ('Peta kartica', 2);